### ISSUE TITLE
Exercise_05_23 is wrong!

### ISSUE THREAD

**Issue by SquirrelCoder** [jsquared21/Intro-to-Java-Programming#2]
There should be two different sums, if not the the final sum will be added to the first sum and thus wrong output.

**Comment by jsquared21** [comment]
Thanks will try and correct.

**Comment by SleekPanther** [comment]
Looks like you fixed it. Go ahead & close the issue

**Comment by SquirrelCoder** [comment]
Wow, that was fast, thanks a lot man. :)
