### ISSUE TITLE
-_-

### ISSUE THREAD

**Issue by Joker666** [jsquared21/Intro-to-Java-Programming#28]
YOU ARE WRONG! For you I got scolded from my GF, 1.10 you have wrong answer. See the real solution https://www.cscprogrammingtutorials.com/2015/11/program-to-calculate-average-speed-in-miles.html

**Comment by HeberTorres** [comment]
Lol, my mistake, do your maths before you copy/paste from the internet.

**Comment by Joker666** [comment]
Lol I must have been immature to comment like that, closing now
