### ISSUE TITLE
Exercise_05_34 Answer!

### ISSUE THREAD

**Issue by SquirrelCoder** [jsquared21/Intro-to-Java-Programming#3]
Hey man,

I could not find your answer to Question No. 34 Chapter 5.
This is my answer, though I am not sure, if it's efficient or not. (Still learning :D)
If you like, you may add it to the answers :).

```
    public static void main(String[] args) {
        // Scissor (0)
        // Rock (1)
        // Paper (2)
        Scanner input = new Scanner(System.in);

        int computerItem;
        int numOfComputerWon = 0;
        int numOfHumanWon = 0;

        while (true) {
            System.out.print("Number of Your Points: " + numOfHumanWon);
            System.out.print("\nNumber of Computer Points: " + numOfComputerWon);
            System.out.println();
            System.out.println();
            System.out.print("The Computer is: ");
            computerItem = (int) (Math.random() * 3);
            switch (computerItem) {
                case 0:
                    System.out.print("Scissor");
                    break;
                case 1:
                    System.out.print("Rock");
                    break;
                case 2:
                    System.out.print("Paper");
                    break;
            }
            System.out.println();
            System.out.print("Scissor (0), Rock (1), Paper (2): ");
            int humanItem = input.nextInt();
            System.out.print("You are ");
            switch (humanItem) {
                case 0:
                    System.out.print("Scissor");
                    break;
                case 1:
                    System.out.print("Rock");
                    break;
                case 2:
                    System.out.print("Paper");
                    break;
            }

            System.out.println();

            if (humanItem == 0 && computerItem == 2) {
                numOfHumanWon++;
                System.out.print("You Won! 1 Point for You!");
            } else if (humanItem == 2 && computerItem == 0) {
                numOfComputerWon++;
                System.out.print("You Lost! 1 Point for Computer!");
            } else if (humanItem == 1 && computerItem == 0) {
                numOfHumanWon++;
                System.out.print("You Won! 1 Point for You!");
            } else if (humanItem == 0 && computerItem == 1) {
                numOfComputerWon++;
                System.out.print("You Lost. 1 Point for Computer!");
            } else if (humanItem == 2 && computerItem == 1) {
                numOfComputerWon++;
                numOfHumanWon++;
                System.out.print("You Won! 1 Point for You!");
            } else if (humanItem == 1 && computerItem == 2) {
                numOfComputerWon++;
                System.out.print("You Lost! 1 Point for Computer!");
            } else {
                System.out.print("Draw! Again.");
            }
            System.out.println();
            if (numOfComputerWon - numOfHumanWon >= 2) {
                System.out.print("Computer has " + (numOfComputerWon - numOfHumanWon) + " Points more than you.");
                System.out.print("\nYou Lost. Maybe Next Time!");
                break;
            }
        }
    }
```

**Comment by jsquared21** [comment]
Hmmm Exercise_05_34 was there. Looks like it disappeared, I will push to master again. Thanks!

**Comment by jsquared21** [comment]
Here is the code i did
/*
(Game: scissor, rock, paper) Programming Exercise 3.17 gives a program that
plays the scissor-rock-paper game. Revise the program to let the user continuously
play until either the user or the computer wins more than two times than its
opponent.
*/
import java.util.Scanner;

public class Exercise_05_34 {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);

		int computerWins,					// Counts he number of computer Wins
			 userWins;						// Counts the number of users Wins
		computerWins = userWins = 0; 	// Set acummulators to 0

		do {
			// Generate a random integer 0, 1, or 2
			int computer = (int)(Math.random() * 3);
	
			// Prompt the user to enter a number 0, 1, or 2
			System.out.print("scissor (0), rock(1), paper (2): ");
			int user = input.nextInt();
	
			System.out.print("The computer is ");
			switch (computer)
			{
				case 0: System.out.print("scissor."); break;
				case 1: System.out.print("rock."); break;
				case 2: System.out.print("paper."); break;
			}
	
			System.out.print(" You are ");
			switch (user)
			{
				case 0: System.out.print("scissor"); break;
				case 1: System.out.print("rock"); break;
				case 2: System.out.print("paper"); break;
				default : System.out.println(
					"disqualified for entering an invalid number.");
					System.exit(1);
			}
	
			// Display result 
			if (computer == user)
				System.out.println(" too, It is a draw");
			else
			{
				boolean win = (user == 0 && computer == 2) ||
								  (user == 1 && computer == 0) ||
								  (user == 2 && computer == 1);
				if (win)
				{
					System.out.println(". You won");
					computerWins++; // Increment computer wins
				}
				else
				{
					System.out.println(". You lose");
					userWins++;		// Increment user wins
				}
				
			}
			// Print Score
			System.out.println("Computer wins: " + computerWins +
				"\nUser wins: " + userWins);

			// If either the user or the computer wins  
			// are less than or equal to 2 continue play.
		} while (Math.abs(computerWins - userWins) <= 2);
	}
}

**Comment by SquirrelCoder** [comment]
Cool, thanks mate.
