### ISSUE TITLE
Logic Problem with Exercise_06_19

### ISSUE THREAD

**Issue by SquirrelCoder** [jsquared21/Intro-to-Java-Programming#4]
Hi,

I think this statement is wrong: `side1 + side2 > side3 || side1 + side3 > side2 || side2 + side3 > side1;`
for example take the sides as follow:  side1 == 5, side2 == 21 and side3 == 6, there is no way to compute this value, even though the `boolean isValid` method, evaluates to `true`, which should evaluates to `false`!

I think this is the right statement: `side1 + side2 > side3 && side1 + side3 > side2 && side2 + side3 > side1;`

btw, this method could be written as follow too:

```
public static boolean isValid(double side1, double side2, double side3) {
        return side1 + side2 > side3 && side1 + side3 > side2 && side2 + side3;
    }
```

**Comment by jsquared21** [comment]
Hi,
A triangle with side side1 == 5, side2 == 21 and side3 == 6, is an impossible triangle. However,
the question asks that method isValid return true if the sum of any two sides are greater than the third side. 
If side1 == 5, side2 == 21 and side3 == 6,
side1 + side2 = 5 + 21 = 26
26 is greater than 6 so the method must return true 

Your method side1 + side2 > side3 && side1 + side3 > side2 && side2 + side3 > side1 returns false if the sum of any two sides is less than the third side, which i think is wrong.

This method could be written as follow:
public static boolean isValid(double side1, double side2, double side3) {
        return side1 + side2 > side3 || side1 + side3 > side2 || side2 + side3;
}

keep up the coding and feel free to comment anytime!

**Comment by SquirrelCoder** [comment]
Thanks man for the reply.
As you have stated, _the question asks that method isValid return true if the sum of any two sides are greater than the third side_, which means your code is completely correct, regarding what the question wanted.

**Comment by jsquared21** [comment]
No i am wrong and your completely correct.
I have been read the question wrong.
It must return true for all the tests so the && operator must be used instead of ||.
I will correct. Thanks.
