### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by JStephens33** [jsquared21/Intro-to-Java-Programming#8]
Hi, how are you? I have been looking at your code since around last November in 2016, and I would like to upload some of my own exercises which have been derived from a variety of your programs. The format would look similar to code academy and hacker rank. However, individuals would copy and paste the code that I upload, and fill in the blanks missing in the program in order to get it to work. Each uploaded code would basically function like a tutorial.
However, I have noticed that you do not have a license. This means that I am unable to use anything that has been derived from your code. I am writing to you hoping that you respond and that you allow me to upload code onto github that has been derived from your programs.

Thank you for your time.

**Comment by RedPartizane** [comment]
Hi Stephens. I am good thank you. Please feel free to use my codes. That
will not be problem for me. Are you looking for teammate for your system ?
If yes, I would be happy to help you. Have nice day !

2017-02-13 23:27 GMT+03:00 JStephens33 <notifications@github.com>:

**Comment by jsquared21** [comment]
Hi, I am good. I have added a MIT License to my repo. Please feel free to use my code.
